[package]
name = "rust_server_controller"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ansi_escapers = "0.2.0"
async-std = { version = "1.12.0", features = ["tokio03", "tokio02", "tokio1"] }
axum = { version = "0.8.9", features = ["tracing", "ws", "macros"] }
axum-server = { version = "0.8.0", features = ["tls-rustls"] }
axum-extra = "0.10.1"
colorlab = {git = "https://github.com/SturdyFool10/ColorLab.git"}
crossterm = "0.29.0"
futures = "0.3.28"
futures-util = "0.3.28"
h3 = "0.0.8"
h3-axum = "0.2.0"
h3-quinn = "0.0.10"
regex = "1.10.2"
rcgen = "0.13.2"
serde = { version = "1.0.183", features = ["derive", "serde_derive"] }

serde_json = { version = "1.0.105", features = ["float_roundtrip"] }

rmp-serde = "1.1.2"
rmpv = "1.0.0"
quinn = "0.11.9"
rusqlite = { version = "0.32.1", features = ["bundled"] }
rustls-acme = { version = "0.15.1", features = ["axum", "tokio", "webpki-roots", "ring"] }
rustls = "0.23.40"
tokio = { version = "1.31.0", features = ["full", "tracing"] }
tokio-stream = { version = "0.1.14", features = ["net"] }

tokio-tungstenite = { version = "0.27.0", features = ["rustls-tls-webpki-roots"] }

tower = { version = "0.5.2", features = ["full", "tokio"] }

tower-http = { version = "0.6.6", features = ["full", "trace"] }

tracing = "0.1.37"

tracing-subscriber = { version = "0.3.17", features = ["env-filter"] }

dashmap = "6.1.0"
uuid = { version = "1.7.0", features = ["v4"] }

hyper = "1.9.0"

chrono = { version = "0.4.42", features = ["serde"] }

once_cell = "1.21.3"
pem = "3.0.6"

colored = "3.0.0"
ring = "0.17.14"
url = "2.5.4"
webauthn-rs = "0.6.1-dev"
wasmtime = "44.0.1"


[target.'cfg(target_os = "windows")'.build-dependencies]
winres = "0.1"
