window.RSC_CONSTANTS = Object.freeze({
  animation: Object.freeze({
    menuMs: 250,
    overlayMs: 350,
    dropdownMs: 250,
    arrowMs: 100,
    themeTransitionMs: 300,
    saveFeedbackMs: 800,
    reconnectMs: 1000,
    retryMs: 100,
  }),
  commands: Object.freeze({
    historyLimit: 25,
    start: "start",
  }),
  messages: Object.freeze({
    configJsonTypes: Object.freeze([
      "requestConfig",
      "getConfig",
      "ConfigInfo",
      "ConfigChange",
      "configChange",
      "getThemesList",
      "getThemeCSS",
    ]),
    requestInfo: "requestInfo",
    requestConfig: "requestConfig",
    stdinInput: "stdinInput",
    startServer: "startServer",
    killServer: "killServer",
    restartServer: "restartServer",
    terminateServers: "terminateServers",
    configChange: "configChange",
    getThemesList: "getThemesList",
    getThemeCSS: "getThemeCSS",
  }),
  selectors: Object.freeze({
    currentThemeStyleId: "current-theme",
    themeSelectorId: "theme-selector",
    themeContainer: ".theme-container",
    themeLoading: ".theme-loading",
    innerTopBar: ".innerTopBar",
    menu: "#menu",
    mainContent: "#main-content",
    overlay: ".overlay",
    grad: ".grad",
    serverList: ".centerMenu.servers",
  }),
  themeStorage: Object.freeze({
    selectedTheme: "selectedTheme",
    themeCss: "themeCSS",
  }),
  uiText: Object.freeze({
    inactiveSuffix: "(inactive)",
    loading: "Loading...",
    startingServer: "Starting server, please wait...",
    power: "Power",
    restart: "Restart",
    kill: "Kill",
    stdinPlaceholder: "place input for STDIn here...",
    submit: "Submit",
  }),
  webgl: Object.freeze({
    fallbackRgb: Object.freeze([30, 30, 50]),
    decayRate: 50.0,
  }),
});
